#include <furi.h>
#include <gui/gui.h>

/* generated by fbt from .png files in images folder */
#include <flipper_ecu_icons.h>

typedef struct {
    ViewPort* view_port;
    Gui* gui;
    FuriMessageQueue* event_queue;
} FlipperECUApp;

static void flipper_ecu_app_draw_callback(Canvas* canvas, void* ctx) {
    UNUSED(ctx);
    canvas_clear(canvas);
    canvas_set_font(canvas, FontSecondary);
    canvas_draw_str(canvas, 51, 32, "Fuck U!");
}
static void flipper_ecu_app_input_callback(InputEvent* input_event, void* ctx) {
    FuriMessageQueue* event_queue = ctx;
    furi_message_queue_put(event_queue, input_event, FuriWaitForever);
}

FlipperECUApp* flipper_ecu_app_alloc(void) {
    FlipperECUApp* app = malloc(sizeof(FlipperECUApp));

    app->view_port = view_port_alloc();
    app->event_queue = furi_message_queue_alloc(8, sizeof(InputEvent));
    view_port_draw_callback_set(app->view_port, flipper_ecu_app_draw_callback, NULL);
    view_port_input_callback_set(app->view_port, flipper_ecu_app_input_callback, app->event_queue);

    app->gui = furi_record_open(RECORD_GUI);
    gui_add_view_port(app->gui, app->view_port, GuiLayerFullscreen);

    return app;
}

void flipper_ecu_app_free(FlipperECUApp* app) {
    furi_message_queue_free(app->event_queue);
    gui_remove_view_port(app->gui, app->view_port);
    furi_record_close(RECORD_GUI);
    view_port_free(app->view_port);
    free(app);
}

void flipper_ecu_app_run(FlipperECUApp* app) {
    while(1) {
        InputEvent event;
        furi_check(
            furi_message_queue_get(app->event_queue, &event, FuriWaitForever) == FuriStatusOk);
        if(event.key == InputKeyBack) {
            break;
        }
    }
}

int32_t flipper_ecu_app(void* p) {
    UNUSED(p);
    FlipperECUApp* app = flipper_ecu_app_alloc();
    flipper_ecu_app_run(app);
    flipper_ecu_app_free(app);

    return 0;
}
